name: Verify File

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    # env:
    #   STAGE: dev
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_WF != '' }}
    steps: 
      - uses: actions/checkout@v3
      - run: |
          [[ -f ${{ vars.FILE_TO_CHECK }}]] || ( echo "${{ vars.FILE_TO_CHECK }} file needs to be added to ${{ github.repository }} !" && exit 1 )
