name: Verify File

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  PIPE: cicd

jobs:
  verify:
    # env:
    #   STAGE: dev
    environment:
      name: dev
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_WF }} == 'true'
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: |
          [[ -f ${{ vars.FILE_TO_CHECK }} ]] || ( echo "${{ vars.FILE_TO_CHECK }} file needs to be added to ${{ github.repository }} !" && exit 1 )
    
  environments:
      env:
        STAGE: dev
      runs-on: ubuntu-latest
      steps:
        - name: create item with token
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: | 
            echo "${{ env.PIPE }}"
            echo "${{ env.STAGE }}"
            echo "${{ env.GITHUB_TOKEN }}"
